version: "3"
services:
    app:
        build:
            context: .
        expose:
            - 8000
        volumes:
            - ./:/app
        command: >
            sh -c "python manage.py collectstatic --no-input &&
                   python manage.py migrate &&
                   gunicorn presento_service.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - .env
        restart: always

    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:80"
        depends_on:
            - app
